#!/usr/bin/env bash
#
# Compiles the gamemode into server/gamemodes/.
#
#   tools/server-build.sh            # SQLite build (default, zero configuration)
#   tools/server-build.sh --mysql    # MySQL build (needs the MySQL plugin at runtime)
#   tools/server-build.sh --debug    # full symbolic info, for crashdetect
#
# The database driver is a compile-time choice. Gameplay code only ever calls
# the abstraction in server/pawn/core/db.inc, so both builds come from identical
# sources.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR="$ROOT/vendor"
PAWNCC="$VENDOR/pawncc/bin/pawncc"

DRIVER=sqlite
OUT=""
DEBUG_FLAGS="-d1"

for arg in "$@"; do
	case "$arg" in
		--mysql)   DRIVER=mysql ;;
		--sqlite)  DRIVER=sqlite ;;
		--debug)   DEBUG_FLAGS="-d3" ;;
		-o=*)      OUT="${arg#-o=}" ;;
		-h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
		*) echo "unknown option: $arg" >&2; exit 2 ;;
	esac
done

[ -x "$PAWNCC" ] || { echo "pawncc missing — run tools/server-setup.sh first" >&2; exit 1; }

case "$DRIVER" in
	mysql)  [ -n "$OUT" ] || OUT="$ROOT/server/gamemodes/gtasan-mysql.amx" ;;
	sqlite) [ -n "$OUT" ] || OUT="$ROOT/server/gamemodes/gtasan.amx" ;;
esac

mkdir -p "$(dirname "$OUT")"

# The driver is selected through a generated header rather than a pawncc
# command-line constant: those define constants, not preprocessor macros, so
# `#if defined ...` on them is not dependable.
cat > "$ROOT/server/pawn/core/db_driver.inc" <<EOF
// Generated by tools/server-build.sh — do not edit, do not commit.
#define DB_USE_$(echo "$DRIVER" | tr '[:lower:]' '[:upper:]')
EOF

echo "==> compiling $DRIVER build -> ${OUT#"$ROOT"/}"

# libpawnc.so sits next to the binary when pawncc is built from source.
export LD_LIBRARY_PATH="$(dirname "$PAWNCC"):${LD_LIBRARY_PATH:-}"

set +e
"$PAWNCC" "$ROOT/server/pawn/gamemode.pwn" \
	-o"$OUT" \
	-i"$VENDOR/include" \
	-i"$ROOT/server/pawn" \
	-\;+ -O1 "$DEBUG_FLAGS" -v2
status=$?
set -e

[ $status -eq 0 ] || { echo "==> build FAILED" >&2; exit $status; }
echo "==> build OK: ${OUT#"$ROOT"/}"
